apiVersion: v1
kind: Pod
metadata:
  name: nginx-mozilla-pod
  labels:
    app: multi-container
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: mozilla
      image: jlesage/firefox
      ports:
        - containerPort: 5800
